### ISSUE TITLE
can drop the network policy config after next Dask-gateway release

### ISSUE THREAD

**Issue by bolliger32** [RhodiumGroup/daskhub-rhg-config#4]
once next Dask-gateway version is released, we shouldn't need to add the networkPolicy config currently in `values-prod.yaml`: https://github.com/dask/dask-gateway/pull/352

**Comment by brews** [comment]
Do you know if this is going to break things, @bolliger32 ?

**Comment by bolliger32** [comment]
@brews I don't know for sure, since there hasn't been a Dask-gateway release with this change incorporated. It would certainly break the current deployment if we removed it right now. I think once Dask-gateway 0.9.1 comes out (or 0.10), it won't hurt to have this section in there but we will be free to remove it without breaking things at that point

**Comment by brews** [comment]
This test cluster and deployment are no longer operational. I am closing this issue and switching this repo to a public archive. Thank you!
